 current_dir := ${CURDIR}
 TOP := SoCNow
 SOURCES := ${current_dir}/SoCNow.v \
	   ${current_dir}/PLL_8MHz.v \
	   ${current_dir}/clk_wiz_0_clk_wiz.v
 
 # Include your constraint file path(s) below. Use either an XDC file
 # or a PCF+SDC pair. Don't use all three file types.
 XDC := ${current_dir}/arty.xdc
 
include /home/mordok/f4pga-examples/common/common.mk
