# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Make all SoC Combinations
      run: python3 soc_test.py all
    - name: setup F4PGA/Symbiflow
      run: ./f4pga_setup.sh
    - name: Run Bitstream on all SoC Combinations
    - run: ./bitstream_runner.sh
