# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Automated Bitstream Gen Tester

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Make all SoC Combinations
      run: python3 soc_test.py all
    - name: Setup F4PGA/Symbiflow
      run: ./f4pga_setup.sh
    - name: Run Bitstream on all SoC Combinations
      run: ./bitstream_runner.sh
